/* topics.js — the ordered registry of all visualizations.
   Used by shell.js to build the header, the prev/next nav, and by index.html. */
window.POLY_TOPICS = [
  { n: '01', id: '01-iteration-space', file: '01-iteration-space.html',
    title: '반복 공간과 스케줄', en: 'Iteration Domain & Schedule',
    blurb: '폴리헤드럴 모델의 세 재료 — 반복 영역(정수 다면체), 스케줄(시간 도장 = 변환행렬), 접근 함수.',
    tags: ['domain', 'schedule θ', 'affine.for'] },
  { n: '02', id: '02-interchange', file: '02-interchange.html',
    title: '루프 순서 교환', en: 'Loop Interchange',
    blurb: '스케줄 행렬의 치환으로 순회 순서를 바꿔 캐시 stride·지역성을 개선한다.',
    tags: ['permutation', 'locality', 'stride'] },
  { n: '03', id: '03-fusion', file: '03-fusion.html',
    title: '루프 융합', en: 'Loop Fusion',
    blurb: '두 반복 영역을 한 루프로 합쳐 producer–consumer 지역성을 높이고 중간 버퍼를 줄인다.',
    tags: ['fusion', 'producer-consumer', 'reuse'] },
  { n: '04', id: '04-tiling', file: '04-tiling.html',
    title: '루프 타일링', en: 'Loop Tiling (Cache Locality)',
    blurb: 'strip-mine + interchange로 반복 공간을 타일로 쪼개 워킹셋을 캐시에 가둔다.',
    tags: ['tiling', 'strip-mine', 'cache'] },
  { n: '05', id: '05-paging', file: '05-paging.html',
    title: '타일링과 페이징 / TLB', en: 'Tiling for Paging & TLB',
    blurb: '반복 타일을 데이터 페이지에 정렬해 page fault·TLB miss를 줄인다.',
    tags: ['paging', 'TLB', 'memory'] },
  { n: '06', id: '06-parallel', file: '06-parallel.html',
    title: '의존성 분석과 병렬화', en: 'Dependence Analysis → affine.parallel',
    blurb: 'loop-carried dependence가 없으면 affine.for가 affine.parallel이 된다.',
    tags: ['dependence', 'affine.parallel', 'parallelism'] },
  { n: '07', id: '07-skewing', file: '07-skewing.html',
    title: '스큐잉과 웨이브프론트 병렬성', en: 'Skewing → Wavefront Parallelism',
    blurb: '없던 병렬성을 만든다 — 스큐 스케줄 t=i+j로 의존성을 시간축으로 밀어 wavefront를 병렬화.',
    tags: ['skewing', 'wavefront', '★ 핵심'] },
  { n: '08', id: '08-simd', file: '08-simd.html',
    title: 'SIMD 벡터화', en: 'SIMD Vectorization',
    blurb: '병렬 안쪽 루프를 벡터 폭 VL로 묶어 한 벡터 op이 VL개 반복을 처리한다.',
    tags: ['SIMD', 'vector', 'lanes'] },
  { n: '09', id: '09-multicore', file: '09-multicore.html',
    title: '멀티코어 분배', en: 'Multicore Distribution & Speedup',
    blurb: '바깥 병렬 루프·타일을 P개 코어에 block/cyclic 분배 — makespan과 speedup.',
    tags: ['cores', 'block/cyclic', 'speedup'] },
  { n: '10', id: '10-pipeline', file: '10-pipeline.html',
    title: '소프트웨어 파이프라이닝', en: 'Software Pipelining',
    blurb: '연속 반복의 스테이지를 겹쳐 II 간격으로 발사 — prologue·steady-state·epilogue.',
    tags: ['pipeline', 'II', 'overlap'] }
];
